### ISSUE TITLE
The gas limit is too large

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/wormhole-pro#139]
### Prerequisites

- [X] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

Low

### Description

The Pangolin Smart => Pangoro，when send transaction using wallet, its gas limit configured as 21_000_000, it's too large.

### How to reproduce this issue

call Pangolin Smart => Pangoro transfer

### Actual behavior

gaslimit=21000000

### Expected behavior

need a reasonable gaslimit

**Comment by sxlwar** [comment]
```js
const gas = await web3.eth.estimateGas({ to: mappinAddress}) //  mappinAddress: 0xdc552396caec809752fed0c5e23fd3983766e758
```
resolved gas value is: 25655

metamask display:
![image](https://user-images.githubusercontent.com/20088392/137238069-0b867c52-33ce-4244-8838-3d09b1176904.png)

obviously, the unit is wrong

I have tried to pass data params, but the result is the same as before

```js
const data = web3.eth.abi.encodeParameters(
        ['uint32', 'uint64', 'address', 'bytes', 'uint256'],
        [specVersion, weight, asset.address, receiver, amount]
      );
const gas = await web3.eth.estimateGas({ to: mappinAddress, data }) //  mappinAddress: 0xdc552396caec809752fed0c5e23fd3983766e758
```

encoded data 
`0x0000000000000000000000000000000000000000000000000000000000000a640000000000000000000000000000000000000000000000000000000029229808000000000000000000000000368b27b3ae3eb885266fce70896a7e5c54c93c1e00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000b2d05e00000000000000000000000000000000000000000000000000000000000000002088d388115bd0df43e805b029207cfa4925cecfb29026e345979d9b0004466c49`
