### ISSUE TITLE
切换中英文时，提示信息未变更语言

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/wormhole-pro#8]
![image](https://user-images.githubusercontent.com/25447002/128011630-41d85490-19d8-4c0f-841a-477e1485cd0e.png)

可能是同一个问题：https://github.com/darwinia-network/wormhole-pro/issues/1#issuecomment-891697794

**Comment by sxlwar** [comment]
https://github.com/ant-design/ant-design/issues/20704
